version: '3.9'

services:
  treepoint:
    build:
      context: .
      dockerfile: Dockerfile
    image: treepoint
    environment:
      - RUNTIME_ENV=staging
    volumes:
      - ./:/code
    ports:
      - "80:80"
    links:
      - mysql
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlsecret
    volumes:
      - ./init.sql:/var/init.sql
      - ./db/mysql:/var/lib/mysql
    command: --init-file /var/init.sql
    ports:
      - "3306:3306"
