version: '3.9'

services:
  treepoint:
    build:
      context: .
      dockerfile: Dockerfile
    image: treepoint
    environment:
      - RUNTIME_ENV=staging
    volumes:
      - ./:/code
    ports:
      - "80:80"
    depends_on:
      - mysql
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlsecret
    volumes:
      - ./db/mysql:/var/lib/mysql
    ports:
      - "3306:3306"